[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:tor]
command=/usr/bin/tor -f /config/torrc
user=torproxy
autostart=true
autorestart=true
stdout_logfile=/var/log/tor/tor-stdout.log
stderr_logfile=/var/log/tor/tor-stderr.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=0
startsecs=10

[program:privoxy]
command=/usr/sbin/privoxy --no-daemon /etc/privoxy/config
user=torproxy
autostart=true
autorestart=true
stdout_logfile=/var/log/tor/privoxy-stdout.log
stderr_logfile=/var/log/tor/privoxy-stderr.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=0

[program:webui]
command=/opt/venv/bin/gunicorn --bind 0.0.0.0:8080 --workers 2 --timeout 120 --chdir /app --pid /tmp/gunicorn.pid --access-logfile /var/log/tor/webui-access.log --error-logfile /var/log/tor/webui-error.log "wsgi:app"
user=torproxy
environment=HOME="/var/lib/tor"
autostart=true
autorestart=true
stdout_logfile=/var/log/tor/webui-stdout.log
stderr_logfile=/var/log/tor/webui-stderr.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=0
startsecs=5
